### ISSUE TITLE
run testsimisr.py error

### ISSUE THREAD

**Issue by jinsanko** [jswoboda/RadarDataSim#9]
Please help me to check this problem in running "python testsimisr.py"
Thank.

Traceback (most recent call last):
  File "/home/jsk/code/SimISR/SimISR/runsim.py", line 311, in main
    curfunc(basedir,configfile,ex_inputs)
  File "/home/jsk/code/SimISR/SimISR/runsim.py", line 60, in makespectrums
    (sensdict, simparams) = readconfigfile(configfile)
  File "/home/jsk/code/SimISR/SimISR/utilFunctions.py", line 692, in readconfigfile
    angles = getangles(beamlist,config.get('section 1','radarname'))
  File "/home/jsk/code/SimISR/beamtools/bcotools.py", line 28, in getangles
    with tables.open_file(reffile) as f:
  File "/home/jsk/anaconda/lib/python2.7/site-packages/tables/file.py", line 320, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/home/jsk/anaconda/lib/python2.7/site-packages/tables/file.py", line 784, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 337, in tables.hdf5extension.File._g_new
  File "tables/utilsextension.pyx", line 612, in tables.utilsextension.encode_filename
TypeError: Expected bytes, got bool

**Comment by jswoboda** [comment]
I think the issue is you need to install the PythonISRUtilities in develop mode. The problem seems to be that you're missing a file that's supposed to be there.

**Comment by jinsanko** [comment]
Thank. It works fine now.
